@startuml
skinparam roundCorner 10
skinparam shadowing false
skinparam classFontName Lato
skinparam classFontSize 16
skinparam defaultFontName Source Code Pro
skinparam defaultFontSize 14
skinparam ClassAttributeFontStyle normal
skinparam ClassBackgroundColor white
skinparam ClassBorderColor black
skinparam ClassBorderThickness 1
skinparam ArrowColor black
skinparam linetype polyline
class dev.nymann.sensor_server.SensorServer {
+ void start(int)
+ void stop()
}
class dev.nymann.sernsor_server.TestSensorServer {
+ {static} void start()
+ void tryToQuit()
}
@enduml
